# Generated by Django 4.2.1 on 2023-05-07 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0002_rename_question_id_option_question_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="updated_at",
        ),
    ]
