# Generated by Django 4.2.1 on 2023-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("forms", "0003_remove_answer_created_at_remove_answer_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="questionresponse",
            name="response_status",
        ),
        migrations.AddField(
            model_name="form",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
    ]
